### GENERAL SETTINGS ###

# Site settings
title: BRICKTOWNSEO.
seotitle: Oklahoma City SEO Experts | Bricktown SEO
description: "Bricktown SEO is a fast paced software development company with specialties in Oklahoma City SEO (Google Page Ranking), software and web programming, and Google AdWords for the Oklahoma City Metro"
analytics: UA-58465065-1
baseurl: #important: start with /
url: "http://bricktownseo.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: https://facebook.com/BricktownSEO
  - title: twitter
    url: https://twitter.com/BricktownSEO
  - title: youtube
    url: https://youtube.com/BricktownSEO
  - title: google-plus
    url: https://plus.google.com/+Bricktownseo
  - title: linkedin
    url: https://www.linkedin.com/in/bricktownseo
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - 3818 Marked Tree Drive,
    - Edmond, OK, 73013,
    - United States
email: phil@bricktownseo.com
tel: +1 (405) 231-0670


# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "At Bricktown SEO we are always ready to tackle your Oklahoma City SEO projects along with any custom software development. We are available via email, sms, facebook, google, or the good ole' telephone. We look forward to talking to you soon."

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "Phil was amazing! He helped us with rebuilding our website, making it extremely user friendly, and very appealing to the eyes. He taught us a lot of verbiage involving online website making and gave us plenty of tips to assist with the continued growth of our website. He was able to get us to the front page of Yahoo, Bing, and the most sought after Google within about 6 weeks. Not only did he help with our website, but he assisted in coming up with creative events that our clientele would possibly be interested in. He has a amazing skills and expertise involving the internet and web building world. We are looking forward to being able to work with Phil in the future!"
    author: Ali Galeancu
    position: Owner - Royal Limos OKC